### ISSUE TITLE
HTML Validation Issues

### ISSUE THREAD

**Issue by jordanwillis** [stephj41/Colmar#1]
Overall your HTML look really good!  I always like to recommend students run their code through an HTML validator once they feel it is complete in order to catch any silly mistakes or typos.  Here is some feedback regarding a few structure issues that I discovered.

1. Using `style` attribute instead of `type` attribute in `<link>` element.

https://github.com/stephj41/Colmar/blob/ce0bdcb02350384ded6d2e948ce8e44008fdd77a/index.html#L7-L9

The `<link>` element doesn't actually have a valid attribute called `style`, but I am guessing that you had intended to use `type` instead.  The `type` attribute is what instructs the browser the MIME type of the linked file which is uses to determine how it should be parsed and interpreted.  So instead of `style` it should actually be `type="text/css"`.

2. Using an anchor tag (`<a>`) within `<button>`

https://github.com/stephj41/Colmar/blob/master/index.html#L49

The `<button>` attribute is actually only allowed to contain text or images element and cannot contain anchor tags.  To be honest I'm not exactly sure why this is, but I'm guessing it has to do with the button that each element are clickable components.  For something like this, I would just use an anchor tag (since it really is a link) and use CSS to style it accordingly.

``` html
<a href="#" class="button">Start here</a>
```

3. Watch out for forgetting to close elements

There were a few instances where you forgot to close elements, which I'm sure were just typos.

https://github.com/stephj41/Colmar/blob/ce0bdcb02350384ded6d2e948ce8e44008fdd77a/index.html#L205-L206

Also, it looks like your main `.container` element never got closed at the end of the document (this is quite common to forget about since the opening tag is out of view).

https://github.com/stephj41/Colmar/blob/master/index.html#L41

Unfortunately, with larger projects like this, it's easy to suffer from a typo here and there.  Fortunately, we have great tools available to help identify these types of issues, so I encourage you to make this part of your standard workflow if you can!

https://validator.w3.org/nu/?doc=https%3A%2F%2Frawgit.com%2Fstephj41%2FColmar%2Fmaster%2Findex.html

**Comment by stephj41** [comment]
These issues have been corrected and will be merged with next commit
