### ISSUE TITLE
Semantic HTML

### ISSUE THREAD

**Issue by jordanwillis** [stephj41/Colmar#2]
You did a fantastic job incorporating some of the more semantic HTML elements in your code such as `<nav>`, `<header>`, `<footer>`, and `<section>`.  Nice job!

I also really liked your use of unordered lists for your nav bar and footer links.  This is another example of proper semantic HTML because it communicates the appropriate context and structure (which is super important for things like accessibility and screen readers).

**Comment by stephj41** [comment]
Woot ~ thanks again for the review it was super helpful
