### ISSUE TITLE
Use `<video>` instead of `<embed>`

### ISSUE THREAD

**Issue by jordanwillis** [stephj41/Colmar#3]
Another recommendation that I would like to make is to use the `<video>` element instead of `<embed>` when using video.  

https://github.com/stephj41/Colmar/blob/ce0bdcb02350384ded6d2e948ce8e44008fdd77a/index.html#L171-L173

The `<embed>` element is used to embed external content that is provided by an external application or source.  It was used pretty heavily "back in the day" for browser plugins (things like ActiveX, flash, quicktime, etc.), but is really not so relevant anymore since most browsers have deprecated browser plugins.  As a result, in this case, using `<embed>` results in the browser automatically downloading the video file which is not the behavior we want.

Instead, you should use the native`<video>` element which provides the ability to embed a video player that supports the playback of the video directly in the page.  Here is an example of what it would look like.

``` html
<video src="resources/videos/thesis.mp4" controls>
  Video could not be loaded.
</video>
```

With this approach, the user can now view the intended video directly in the page, which is was most users are expecting.  Notice that it's best practice to add some fallback text in case the user's browser doesn't have video support.

**Comment by stephj41** [comment]
This issue has been corrected and will be reflected in the next commit.
