### ISSUE TITLE
Responsive Design - nav bar

### ISSUE THREAD

**Issue by jordanwillis** [stephj41/Colmar#4]
Nice job appropriately using media queries to create a responsive design that optimizes for desktop and mobile!  As I was experimenting with the various breakpoints, I noticed that the desktop version of the nav bar was still being displayed when in "mobile" mode.

It looks like you might just have a typo in your desktop nav bar class name that is preventing your media query from hiding the content.

https://github.com/stephj41/Colmar/blob/ce0bdcb02350384ded6d2e948ce8e44008fdd77a/index.html#L21-L28

https://github.com/stephj41/Colmar/blob/ce0bdcb02350384ded6d2e948ce8e44008fdd77a/resources/mobile.css#L56-L58

Notice that the selector is `#desktop` but your HTML is `desktops`.  One thing to keep in mind though however, is that the value of the `ID` attribute must be unique across your entire page.  So you will want to switch all your "desktop" related elements to use class names instead, like this.

``` html
<div class="logo" class="desktop">
  <img src="./resources/images/ic-logo.svg" alt="School Logo">
  <h1><span id="fancy">COLMAR</span>ACADEMY</h1>
</div>
<nav class="desktop">
  <ul>
    <li><a href="./campus.html" target="_blank">On Campus</a></li>
    <li><a href="./online.html" target="_blank">Online</a></li>
    <li><a href="./companies.html" target="_blank">For Companies</a></li>
    <li><a href="./signin.html" target="_blank">Sign In</a></li>
  </ul>
</nav>
```

Don't forget to update your selector as well from `#desktop` to `.desktop`.

**Comment by stephj41** [comment]
all suggested changes in this issue have been added and will be pushed with the next commit.
