### ISSUE TITLE
CSS Review

### ISSUE THREAD

**Issue by jordanwillis** [stephj41/Colmar#5]
Similar to your HTML, your CSS looks pretty good as well!  Here are a few recommendations that I found.

1. Code style and indentation.

I would highly recommend that you follow the same code style and indentation rules in your CSS as you did in your HTML (your indentation rocked in your HTML!).  Your `style.css` file looks fantastic but be sure to use proper indentation with your media queries in your `mobile.css` file.  As an example, instead of this...

https://github.com/stephj41/Colmar/blob/ce0bdcb02350384ded6d2e948ce8e44008fdd77a/resources/mobile.css#L137-L145

Make sure your code inside each media query is indented the same as if it were a nested element in your HTML.

``` css
@media only screen and (max-width: 1999px) {
  .mobile-embed {
    display: block;
    height: auto;
    width: 100%;
    padding: 0;
  }
}
```

This not only makes your code highly readable (which is super important especially for large projects or projects with several people), but also ensures that you don't forget to close a media query like you did on your `max-width: 1200px` breakpoint.

https://github.com/stephj41/Colmar/blob/master/resources/mobile.css#L43

Notice that there is no closing bracket before you declared your next break point.

https://github.com/stephj41/Colmar/blob/ce0bdcb02350384ded6d2e948ce8e44008fdd77a/resources/mobile.css#L132-L139

2. Watch out for invalid CSS property values and incorrect property value formats. 

https://github.com/stephj41/Colmar/blob/master/resources/style.css#L69

`font-weight` must either have a 3 digit number ranging from 100 to 900 or use one of a handful of text based constant values (e.g. normal, bold, bolder, etc.).  https://www.w3schools.com/CSSref/pr_font_weight.asp

https://github.com/stephj41/Colmar/blob/master/resources/style.css#L131

Don't forget to use spaces for your `padding`/`margin` value delimiters instead of commas

https://github.com/stephj41/Colmar/blob/master/resources/style.css#L174

Unlike some other similar CSS properties, `max-width` does not accept a value of `auto`.  You can use one of the below possible values instead.

`max-width: none|length|initial|inherit`

**Comment by stephj41** [comment]
recommeded changes completed and will be be added with next commit.
