### ISSUE TITLE
Summary: Grade = Meets Expectations

### ISSUE THREAD

**Issue by jordanwillis** [stephj41/Colmar#6]
Overall you did a fantastic job on this project!  You demonstrated that you are able to build a website from scratch based only on a static specification that includes complex flexbox layouts and a responsive design.  This is not a trivial feat, so nice work!

I really liked your attention to semantics and loved that you used ID and class names that were meaningful and describe the purpose of intent of the content (instead of using style related or arbitrary names).  This further enhances semantics.

Really, most of the issues that I found were minor typo or structural related things that are fortunately each to guard against by using the right tools.  Watch out for that `<embed>` tag and don't forget to take full advantage of `<video>` instead.

Lastly, I really liked the stylistic flair that you incorporated to the site.  It was enjoyable seeing some of your own personal artistic expression.

Keep up the great work!

**Comment by stephanieaj** [comment]
@jordanwillis Thank you so much for the thorough evaluation.  I will spend some time and work these issues out for this project!
